### PR TITLE
+1 Vote for Jayant

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by NS007-dev — CHANGES_REQUESTED** [review]
@sumitmukharjeeeeee it shows you have voted for Tran Nguyen Thuong, but on your PR title and commit it says you want to vote for Jayant? 
Also, this pr will be merged when we get two more entries. Maybe you could take part if you wanted?
Thank you.

**Comment by sumitmukharjeeeeee** [comment]
I did not see the mistake before, However I have made correct vote to Jayant now.
.

**Comment by sumitmukharjeeeeee** [comment]
Also, I have a doubt if you can help me with this. 
If I have 2 commits, just like in this repo then is there a way that can  delete the first commit?
Or I have to run git reset hard HEAD^^ which deletes both the commit

**Review by NS007-dev — APPROVED** [review]
Looks good. Will merge once the last two places are filled. Thanks.

**Review by NS007-dev — COMMENTED** [review]
@sumitmukharjeeeeee if you wish to change your vote, you can otherwise I will merge this. Thank you.

**Comment by sumitmukharjeeeeee** [comment]
> @sumitmukharjeeeeee if you wish to change your vote, you can otherwise I will merge this. Thank you.

My vote goes for jayant only. You can move forward

**Pull request merged**
